import { Manrope, Red_Hat_Display } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/store/provider';
import { Toaster } from 'react-hot-toast';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

const redHatDisplay = Red_Hat_Display({
  variable: '--font-red-hat-display',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata = {
  title: 'DailyWealth4U',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/icons/Logo.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} ${redHatDisplay.variable}`}>
      <body>
        <StoreProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 2500,
              style: {
                background: '#0a1a1a',
                color: '#fafafa',
                border: '1px solid rgba(255,255,255,0.1)',
                fontFamily: 'var(--font-manrope)',
                fontSize: '14px',
              },
            }}
          />
        </StoreProvider>
      </body>
    </html>
  );
}
